# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test simulation runs
#
# See sel4test-sim/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test-Sim

on:
  workflow_call:
    inputs:
      labels:
        required: false
        type: string
      concurrency_group:
        required: true
        type: string
      workflow_call_repo:
        required: true
        type: string
      workflow_call_branch:
        required: true
        type: string
      workflow_call_workflow:
        required: true
        type: string

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.workspace }}
    - run: echo ${{ github.workflow }}-sel4sim-pr-${{ github.event.number }}
    - env:
        github_JSON: ${{ toJSON(github) }}
      run: echo ${GITHUB_WORKSPACE}
    - run: ls -la /home/runner
    - run: ls -la /home/runner/runners
    - run: ls -la /home/runner/work
    - run: ls -la /home/runner/work/_PipelineMapping/axel-h
    - run: ls -la /home/runner/work/_temp

  sim:
    name: Simulation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        march: [armv7a, armv8a, nehalem, rv32imac, rv64imac]
        compiler: [gcc, clang]
    steps:
    - uses: ${{ inputs.workflow_call_repo }}/ci-actions/sel4test-sim@${{ inputs.workflow_call_branch }}
      with:
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
