# Copyright 2022, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# Build and run sel4bench on pull requests, on label request

name: seL4Bench-HW

on:
  workflow_call:
    inputs:
      labels:
        required: false
        type: string
      concurrency_group:
        required: true
        type: string
      workflow_call_repo:
        required: true
        type: string
      workflow_call_branch:
        required: true
        type: string
      workflow_call_workflow:
        required: true
        type: string

# intended to run on
#  pull_request_target:
#    types: [opened, reopened, synchronize, labeled]

# downgrade permissions to read-only as you would have in a standard PR action
permissions:
  contents: read

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.workspace }}
    - env:
        inputs_JSON: ${{ toJSON(inputs) }}
        github_JSON: ${{ toJSON(github) }}
      run: echo ${GITHUB_WORKSPACE}
    - run: ls -la /home/runner
    - run: ls -la /home/runner/runners
    - run: ls -la /home/runner/work
    - run: ls -la /home/runner/work/_PipelineMapping/axel-h
    - run: ls -la /home/runner/work/_temp

  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    if: ${{  contains(inputs.labels, 'hw-bench') }}
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
    - id: repo
      uses: seL4/ci-actions/repo-checkout@master
      with:
        manifest_repo: sel4bench-manifest
        manifest: master.xml
        sha: ${{ github.event.pull_request.head.sha }}

  build:
    name: Build
    needs: code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        march: [armv7a, armv8a, nehalem, rv64imac]
    steps:
    - run: echo ${{ github.workflow }}-sel4bench-build-pr-${{ github.event.number }}-${{ strategy.job-index }}
    - name: Build
      uses: seL4/ci-actions/sel4bench@master
      with:
        xml: ${{ needs.code.outputs.xml }}
        march: ${{ matrix.march }}
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: images-sel4bench-${{ matrix.march }}
        path: '*-images.tar.gz'

  hw-run:
    name: HW Benchmark
    if: ${{ github.repository_owner == 'seL4' }}
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - sabre
          - imx8mm_evk
          - odroid_c2
          - odroid_xu4
          - am335x_boneblack
          - tx1
          - tx2
          - hifive
        include:
          - platform: pc99
            req: skylake
          - platform: pc99
            req: haswell3
    steps:
      - run: echo ${{ github.workflow }}-sel4bench-hw-run-pr-${{ github.event.number }}-${{ strategy.job-index }}
      - name: Get machine queue
        uses: actions/checkout@v4
        with:
          repository: seL4/machine_queue
          path: machine_queue
      - name: Get march
        id: plat
        uses: seL4/ci-actions/march-of-platform@master
        with:
          platform: ${{ matrix.platform }}
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: images-sel4bench-${{ steps.plat.outputs.march }}
      - name: Run
        uses: seL4/ci-actions/sel4bench-hw@master
        with:
          platform: ${{ matrix.platform }}
          req: ${{ matrix.req }}
          index: $${{ strategy.job-index }}
        env:
          HW_SSH: ${{ secrets.HW_SSH }}
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          # funky expression below is to work around lack of ternary operator
          name: sel4bench-results-${{ matrix.platform }}${{ matrix.req != '' && format('-{0}', matrix.req) || '' }}
          path: '*.json'
