# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test simulation runs
#
# See sel4test-sim/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test-Sim

on:
  workflow_call:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - env:
        github_JSON: ${{ toJSON(github) }}
      run: |
        echo ${{ github.workspace }}
        echo ${{ github.workflow }}-sel4sim-pr-${{ github.event.number }}
        echo ${GITHUB_WORKSPACE}
        ls -la /home/runner
        ls -la /home/runner/runners
        ls -la /home/runner/work
        ls -la /home/runner/work/_PipelineMapping/axel-h
        ls -la /home/runner/work/_temp

  sim:
    name: Simulation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        march: [armv7a, armv8a, nehalem, rv32imac, rv64imac]
        compiler: [gcc, clang]
    concurrency:
      group: ${{ github.workflow }}-sel4sim-pr-${{ github.event.number }}-${{ strategy.job-index }}
      cancel-in-progress: true
    steps:
    - uses: seL4/ci-actions/sel4test-sim@master
      with:
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
